2021-06-11 05:40:48,277 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 10390844ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 07:25:38,348 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 6151325ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 09:16:15,117 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 6536719ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 09:57:52,321 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 2319596ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 10:05:26,526 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 354165ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 10:48:24,036 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 797109ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 12:59:22,320 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 2297429ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 13:12:40,552 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 758196ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 14:36:56,130 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 894948ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-11 17:22:14,978 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 557419ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

2021-06-12 06:10:16,474 ERROR 21197 nodejs.ClusterClientNoResponseError: client no response in 43261044ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
name: "ClusterClientNoResponseError"
pid: 21197
hostname: bogon

