2021-06-25 08:09:50,046 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 3829370ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

2021-06-25 11:10:17,331 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 1446029ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

2021-06-25 12:13:21,838 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 643932ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

2021-06-25 18:11:42,499 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 257775ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

2021-06-25 21:17:21,652 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 11139090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

2021-06-25 22:10:16,494 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 429966ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

2021-06-25 22:23:22,502 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 765996ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

2021-06-25 23:09:04,409 ERROR 46260 nodejs.ClusterClientNoResponseError: client no response in 1221658ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 46260
hostname: bogon

